config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  # concern :projectable do
  #   resources :projects
  # end

  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :projects, except: [:create, :new]

  resources :users, only: [:show] do
    resources :projects, only: [:create, :new]
  end

  resources :groups do
    resources :projects, only: [:create, :new]
    post '/add_user' => 'groups#add_user', as: :add_user
    post '/remove_user' => 'groups#remove_user', as: :remove_user
  end

end

app/models/group.rb
class Group < ApplicationRecord
  has_many :groupings, dependent: :destroy
  has_many :users, through: :groupings
  has_many :projects, as: :projectable, dependent: :destroy

  validates :title, presence: true
  validates :description, presence: true

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def index
    @groups = Group.all
  end

  def show
    @group = Group.find(params[:id])
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.users << current_user

    if @group.save
      redirect_to @group
    else
      flash.now[:alert] = "There was an error saving the group. Please try again."
      render 'new'
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])

    if @group.update(group_params)
      redirect_to @group
    else
      render 'edit'
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    redirect_to groups_path
  end

  def add_user
    @group = Group.find(params[:group_id])
    @group.users << current_user

    if @group.save
      flash.now[:alert] = "You've been successfully added to this group."
    else
      flash.now[:alert] = "There was an error adding you to the group. Please try again."
    end
  end

  def remove_user
    @group = Group.find(params[:group_id])
    @group.users.destroy(current_user)

    if @group.save
      flash.now[:alert] = "You've been successfully removed from this group."
    else
      flash.now[:alert] = "There was an error removing you from the group. Please try again."
    end
  end

  private

    def group_params
      params.require(:group).permit(:title, :description)
    end
end

app/views/groups/_form.html.erb
<%= form_for @group do |f| %>

  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@group.errors.count, "error") %> prohibited
        this group from being saved:
      </h2>
      <ul>
        <% @group.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', groups_path %>

app/views/groups/edit.html.erb
<h1>Editing a Group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<h1>All the groups</h1>
<%= link_to 'New group', new_group_path %>
<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Users Count</th>
    <th>Projects Count</th>
  </tr>
  <% @groups.each do |group| %>
    <tr>
      <td><%= group.title %></td>
      <td><%= group.description %></td>
      <td><%= group.users.count %></td>
      <td><%= group.projects.count %></td>
      <td><%= link_to 'Show', group_path(group) %></td>
      <td><%= link_to 'Edit', edit_group_path(group) %></td>
      <td><%= link_to 'Destroy', group_path(group),method: :delete,data: { confirm: 'Are you sure?' } %></td>
      <td><%= link_to 'Add me', group_add_user_path(group), method: :post %></td>
      <td><%= link_to 'Remove me', group_remove_user_path(group), method: :post %></td>
    <tr>
  <% end %>
</table>

app/views/groups/new.html.erb
<h1> New Group </h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<h1> <%= @group.title %></h1>
<p><%= @group.description %></p>
<ul>
<li><%= link_to 'Edit this group', edit_group_path(@group) %></li>
<li><%= link_to 'List all the groups', groups_path %></li>
</ul>
<hr>
<h2>This group has <%= @group.projects.count %> projects</h2>
<ul>
<li><%= link_to 'new group project', new_group_project_path(@group)%></li>
</ul>
<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
  </tr>
  <% @group.projects.each do |project| %>
  <tr>
    <td><%= project.title %></td>
    <td><%= project.description %></td>
    <td><%= link_to 'Show', project_path(project)%></td>
    <td><%= link_to 'Edit', edit_project_path(project)%></td>
    <td><%= link_to 'Delete', project_path(project), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
  <% end %>
</table>
<hr>
<h2>This group has <%= @group.users.count %> users</h2>
<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
  </tr>
  <% @group.users.each do |user| %>
  <tr>
    <td><%= user.name%></td>
    <td><%= user.email%></td>
  </tr>
  <% end %>
</table>

<ul>
<li><%= link_to 'Add me to this group', group_add_user_path(@group), method: :post %></li>
<li><%= link_to 'Remove me from this group', group_remove_user_path(@group), method: :post %></li>
</ul>
<br>