config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  # concern :projectable do
  #   resources :projects
  # end

  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :projects, except: [:create, :new]

  resources :users, only: [:show] do
    resources :projects, only: [:create, :new]
  end

  resources :groups do
    resources :projects, only: [:create, :new]
    post '/add_user' => 'groups#add_user', as: :add_user
    post '/remove_user' => 'groups#remove_user', as: :remove_user
  end

end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :projectable, polymorphic: true

  validates :title, presence: true
  validates :description, presence: true
  # validates :creator, presence: true
  validates :projectable_type, presence: true
  validates :projectable_id, presence: true
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :find_projectable

  def index
    @projects = Project.all
    @user = current_user
  end

  def show
    @project = Project.find(params[:id])
  end

  def new
    @projectable = find_projectable
    @project = @projectable.projects.new

  end

  def create
    @projectable = find_projectable
    @project = @projectable.projects.new(project_params)
    # @project.creator << current_user

    if @project.save
      redirect_to @project
    else
      render :new
    end

  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])

    if @project.update(project_params)
      redirect_to @project.projectable
    else
      render 'edit'
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    redirect_to root_path

  end

  private
    def find_projectable
      if params[:group_id]
        @projectable = Group.find(params[:group_id])
      elsif params[:user_id]
        @projectable = User.find(params[:user_id])
      end
    end

    def project_params
      params.require(:project).permit(:title, :description)
    end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for [@projectable, @project] do |f| %>

  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@project.errors.count, "error") %> prohibited
        this project from being saved:
      </h2>
      <ul>
        <% @project.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing a project</h1>

<%= render 'form' %>

app/views/projects/index.html.erb
<h1>All Group Projects</h1>
<table>
  <tr>
    <th>Group</th>
    <th>Project Title</th>
    <th>Project Description</th>
  </tr>
<% @projects.where(projectable_type: "Group").find_each do |project| %>
  <tr>
    <td><%=project.projectable.title %> </td>
    <td><%=project.title %> </td>
    <td><%=project.description %> </td>
    <td><%= link_to 'Show', project_path(project) %></td>
    <td><%= link_to 'Edit', edit_project_path(project) %></td>
    <td><%= link_to 'Delete', project_path(project),method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
  <% end %>
</table>

<h1>All User Projects</h1>
<%= link_to 'new user-project', new_user_project_path(@user) %>
<br><br>
<table>
  <tr>
    <th>User</th>
    <th>Project Title</th>
    <th>Project description</th>
  </tr>
  <% @projects.where(projectable_type: "User").find_each do |project| %>
  <tr>
    <td><%=project.projectable.email %> </td>
    <td><%=project.title %> </td>
    <td><%=project.description %> </td>
    <td><%= link_to 'Show', user_projects_path(project) %></td>
    <td><%= link_to 'Edit', edit_project_path(project) %></td>
    <td><%= link_to 'Delete', project_path(project),method: :delete,data: { confirm: 'Are you sure?' } %></td>
  </tr>
  <% end %>
</table>
<br>
<br>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

app/views/projects/show.html.erb
<h1> <%= @project.title %></h1>
<p> <%= @project.description %></p>
<ul>
    <%= link_to 'Edit this project', edit_project_path(@project)%>
    <%= link_to 'Delete this project', project_path(@project)%>
</ul>