config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  # concern :projectable do
  #   resources :projects
  # end

  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :projects, except: [:create, :new]

  resources :users, only: [:show] do
    resources :projects, only: [:create, :new]
  end

  resources :groups do
    resources :projects, only: [:create, :new]
    post '/add_user' => 'groups#add_user', as: :add_user
    post '/remove_user' => 'groups#remove_user', as: :remove_user
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The nexchange</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <% if user_signed_in? %>
       Signed in as: <strong><%= current_user.email %></strong> |
       <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
     <% else %>

       <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
       <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
     <% end %>
     <ul class=navbar>
       <li><%=link_to 'Home Page', root_path %> </li>
       <li><%=link_to 'Profile Page', root_path %> </li>
       <li><%=link_to 'Groups Page', groups_path %> </li>
       <li><%=link_to 'Projects Page', projects_path %> </li>
     </ul>
     <hr>
     <%= yield %>
     <hr>
  </body>
</html>